POST http://127.0.0.1:8000/login
Content-Type: application/json

{ "username": "kimNew", "password": "Pass1234!" }

###
POST http://127.0.0.1:8000/signup
Content-Type: application/json

{ "username": "kim4", "password": "Pass1234!", "email": "kim@test.com"
}

###
GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 12a22dcb3cf799bfcabbe75f3fb614e6b9f894f9

{}

###
POST http://127.0.0.1:8000/logout
Content-Type: application/json
Authorization: Token 12a22dcb3cf799bfcabbe75f3fb614e6b9f894f9
