# Generated by Django 5.0.3 on 2024-04-01 19:36

from django.db import migrations

def seed_data(apps, schema_editor):
    Origin = apps.get_model('dumplings', 'Origin')
    Tag = apps.get_model('dumplings', 'Tag')

    Origin.objects.create(country='China')
    Origin.objects.create(country='Japan')
    Origin.objects.create(country='Italy')
    Origin.objects.create(country='Poland')
    Origin.objects.create(country='Tibet')
    Origin.objects.create(country='England')
    Origin.objects.create(country='Russia')
    Origin.objects.create(country='Vietnam')
    Origin.objects.create(country='United States')

    Tag.objects.create(name='Spicy')
    Tag.objects.create(name='Vegan')
    Tag.objects.create(name='Gluten-free')
    Tag.objects.create(name='Savory')
    Tag.objects.create(name='Sweet')
    Tag.objects.create(name='Steamed')
    Tag.objects.create(name='Fried')
    Tag.objects.create(name='Baked')
    Tag.objects.create(name='Dairy-free')
    Tag.objects.create(name='Nut-free')

class Migration(migrations.Migration):

    dependencies = [
        ('dumplings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
