# Generated by Django 5.0.3 on 2024-04-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumplings', '0004_alter_dumpling_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='dumplings',
            field=models.ManyToManyField(blank=True, related_name='tags', to='dumplings.dumpling'),
        ),
    ]
